---
region: 'eu-west-2'
account_id: "579878096224"

component: 'test'
deployment_identifier: "%{hiera('seed')}"

vpc_cidr: "10.1.0.0/16"
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

private_zone_id: 'Z0211739BXR21FNN139O'
