---
region: 'eu-west-2'
account_id: "579878096224"

component: 'test'
deployment_identifier: "%{hiera('seed')}"

vpc_cidr: "10.1.0.0/16"
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

private_zone_id: 'Z0211739BXR21FNN139O'

lambda_function_name: "test-lambda-resource-%{hiera('deployment_identifier')}"
lambda_description: "test terraform-aws-lambda"

lambda_zip_path: 'lambda.zip'
lambda_handler: "handler.hello"
