---
configuration_directory: "%{cwd}/spec/unit/infra/root"
state_file: "%{cwd}/state/root.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  lambda_function_name: "%{hiera('lambda_function_name')}"
  lambda_description: "%{hiera('lambda_description')}"
