---
configuration_directory: "%{cwd}/examples/vpc_access"
state_file: "%{cwd}/state/vpc_access.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  vpc_cidr: "%{hiera('vpc_cidr')}"
  availability_zones: "%{hiera('availability_zones')}"

  private_zone_id: "%{hiera('private_zone_id')}"
